---
- hosts: dev
  become: True
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present

    - name: start docker demon
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python pip
      yum: 
        name: python-pip
        state: present

    - name: Install docker-py module
      pip:
        name: docker-py
        state: present
    
    - name: run docker container
      docker_container:
        name: docker_442
        image: "mahi9618/docker_442:{{DOCKER_TAG}}
        state: started
        published_ports:
            - 0.0.0.0:8080:8080
    
